name: 📄 Technical Documentation

on:
  push:
    branches: [ "main" ]
    paths: [ "docs/technical/**" ]
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    name: "📦 Create technical documentation PDF"
    runs-on: ubuntu-22.04
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Convert to PDF
        uses: docker://pandoc/latex:3.5
        with:
          entrypoint: latexmk
          args: >- 
            -pdf
            -cd
            -lualatex 
            -recorder 
            -jobname=technical-docs 
            -output-directory=./output 
            -interaction=nonstopmode 
            ./docs/technical/main.tex

      - name: 📤 Upload PDF
        uses: actions/upload-artifact@v4
        with:
            name: technical-docs
            path: ./docs/technical/output/technical-docs.pdf
